version: '3.8'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: chemezy
      POSTGRES_PASSWORD: chemezy
      POSTGRES_DB: chemezy
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U chemezy"]
      interval: 30s
      timeout: 10s
      retries: 3

  chemezy-backend:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://chemezy:chemezy@postgres:5432/chemezy
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - .:/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

volumes:
  postgres_data: