"""Add unique constraint to molecular_formula and common_name

Revision ID: 0fa7c5aeac70
Revises: 93e2b9e52fd0
Create Date: 2025-07-16 16:30:48.481831

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '0fa7c5aeac70'
down_revision = '93e2b9e52fd0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chemicals', schema=None) as batch_op:
        batch_op.drop_index(op.f('ix_chemicals_molecular_formula'))
        batch_op.create_index(op.f('ix_chemicals_molecular_formula'), ['molecular_formula'], unique=False)
        batch_op.create_unique_constraint('unique_molecular_formula_common_name', ['molecular_formula', 'common_name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chemicals', schema=None) as batch_op:
        batch_op.drop_constraint('unique_molecular_formula_common_name', type_='unique')
        batch_op.drop_index(op.f('ix_chemicals_molecular_formula'))
        batch_op.create_index(op.f('ix_chemicals_molecular_formula'), ['molecular_formula'], unique=1)
    # ### end Alembic commands ###