"""remove_state_of_product

Revision ID: 93e2b9e52fd0
Revises: 77725fe0ce2b
Create Date: 2025-07-16 10:46:11.288869

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = '93e2b9e52fd0'
down_revision = '77725fe0ce2b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('audit_log')
    op.drop_column('reaction_cache', 'state_of_product')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reaction_cache', sa.Column('state_of_product', sa.VARCHAR(length=100), nullable=False))
    op.create_table('audit_log',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('timestamp', sa.DATETIME(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('action', sa.VARCHAR(), nullable=False),
    sa.Column('details', sqlite.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###