"""add is_admin field to user table

Revision ID: b6c551adbc2e
Revises: c4c7f793b507
Create Date: 2025-07-16 00:12:26.818393

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = 'b6c551adbc2e'
down_revision = 'c4c7f793b507'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'deletionrequest', 'user', ['user_id'], ['id'])
    op.add_column('user', sa.Column('is_admin', sa.Boolean(), nullable=False))
    op.add_column('user', sa.Column('public_profile', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'public_profile')
    op.drop_column('user', 'is_admin')
    op.drop_constraint(None, 'deletionrequest', type_='foreignkey')
    # ### end Alembic commands ###