"""add is_admin field to user table

Revision ID: b6c551adbc2e
Revises: c4c7f793b507
Create Date: 2025-07-16 00:12:26.818393

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = 'b6c551adbc2e'
down_revision = 'c4c7f793b507'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('deletionrequest', schema=None) as batch_op:
        batch_op.create_foreign_key(
            "fk_deletionrequest_user_id_user", 'user', ['user_id'], ['id']
        )

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_admin', sa.Boolean(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('public_profile', sa.Boolean(), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('public_profile')
        batch_op.drop_column('is_admin')

    with op.batch_alter_table('deletionrequest', schema=None) as batch_op:
        batch_op.drop_constraint('fk_deletionrequest_user_id_user', type_='foreignkey')
    # ### end Alembic commands ###