"""Add user_id to deletion_request table

Revision ID: c4c7f793b507
Revises: b5eecbe2a3ba
Create Date: 2025-07-15 22:55:32.967756

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = 'c4c7f793b507'
down_revision = 'b5eecbe2a3ba'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deletionrequest', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_deletionrequest_user_id'), 'deletionrequest', ['user_id'], unique=False)
    # Skip foreign key constraint for SQLite compatibility
    # op.create_foreign_key(None, 'deletionrequest', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_constraint(None, 'deletionrequest', type_='foreignkey')
    op.drop_index(op.f('ix_deletionrequest_user_id'), table_name='deletionrequest')
    op.drop_column('deletionrequest', 'user_id')
    # ### end Alembic commands ###