"""Add state_of_product and explanation to ReactionCache

Revision ID: c4f6ee7355e7
Revises: f09747fe0a7d
Create Date: 2025-07-08 18:24:03.595905

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = 'c4f6ee7355e7'
down_revision = 'f09747fe0a7d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reaction_cache', sa.Column('state_of_product', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True))
    op.add_column('reaction_cache', sa.Column('explanation', sqlmodel.sql.sqltypes.AutoString(length=2000), nullable=True))
    op.drop_column('reaction_cache', 'state_change')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reaction_cache', sa.Column('state_change', sa.VARCHAR(), nullable=True))
    op.drop_column('reaction_cache', 'explanation')
    op.drop_column('reaction_cache', 'state_of_product')
    # ### end Alembic commands ###