"""Add Chemical table

Revision ID: f09747fe0a7d
Revises: 0cae98a8a1fc
Create Date: 2025-07-08 14:02:10.262024

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = 'f09747fe0a7d'
down_revision = '0cae98a8a1fc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chemicals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('molecular_formula', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('common_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('state_of_matter', sa.Enum('SOLID', 'LIQUID', 'GAS', 'PLASMA', 'AQUEOUS', name='stateofmatter'), nullable=False),
    sa.Column('color', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('density', sa.Float(), nullable=False),
    sa.Column('properties', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chemicals_molecular_formula'), 'chemicals', ['molecular_formula'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_chemicals_molecular_formula'), table_name='chemicals')
    op.drop_table('chemicals')
    # ### end Alembic commands ###